### ISSUE TITLE
Editar logo e icone da aba

### ISSUE THREAD

**Issue by felipesqra** [OpenDevUFCG/laguinho#2]
retirar CLI do nome da logo e deixar apenas a imagem no icone da aba

**Comment by davigps** [comment]
# Feito!

![LaguinhoAPIFull](https://user-images.githubusercontent.com/40612788/127563131-c8662123-d693-4408-8920-64544164101a.png)
![LaguinhoAPILogo](https://user-images.githubusercontent.com/40612788/127563133-bdf4be99-d950-4609-b324-94ce2711ab74.png)
![LaguinhoAPIWide](https://user-images.githubusercontent.com/40612788/127563135-c4b2bd20-0922-40e8-bbb4-4b4a817c6319.png)

**Comment by davigps** [comment]
Tá legal assim? @felipesqra

**Comment by felipesqra** [comment]
> Tá legal assim? @felipesqra

Tá perfeitooo @davigsousa
